### ISSUE TITLE
Wrong string sent to resource compiler on windows

### ISSUE THREAD

**Issue by yann64** [aBothe/Mono-D#498]
When compiling a Win32 binary, the following string is used for the resource compiler:
rc.exe /fo "obj\Debug\Resources.Win32Manifest.res" "[Path to solution]\[Project Name]\Resources\Win32Manifest.rc"

Correct string shoul be:
rc.exe /fo "obj\Debug\Resources\Win32Manifest.res" "[Path to solution]\[Project Name]\Resources\Win32Manifest.rc"

There is a "." in place of a "\"

**Comment by dsoronda** [comment]
I would like to fix this problem if you can point me in right direction.

**Comment by aBothe** [comment]
Hasn't this issue been fixed already? [This commit](https://github.com/aBothe/Mono-D/commit/68becefa28c506d8a3b27d0ad0feb6851d48662f) should've done it back then.

**Comment by dsoronda** [comment]
Well, there are 2 problems.
First is that rc.exe should be in path or at least documented as dependency.
Mine is located here : c:\Program Files (x86)\Windows Kits\8.1\bin\x86\rc.exe

2nd problem is after i add above location in my PATH code compiles and gives this errror:

```
Building: x_win32 (Debug)
Performing main compilation...
rc.exe /fo "_PROJECT_PATH_\obj\Debug\Resources.Win32Manifest.res" "_PROJECT_PATH_\Resources\Win32Manifest.rc"
Microsoft (R) Windows (R) Resource Compiler Version 6.3.9600.17298

Copyright (C) Microsoft Corporation.  All rights reserved.


Current dictionary: _PROJECT_PATH_
dmd.exe -debug -gc "main.d" "obj\Debug\Resources.Win32Manifest.res" "kernel32.lib" "gdi32.lib"  "-odobj\Debug" "-of_PROJECT_PATH_\bin\Debug\x_win32.exe" -w -vcolumns -L-L/su:windows -L-L/exet:nt
Build complete -- 1 error, 0 warnings

---------------------- Done ----------------------

Build: 1 error, 0 warnings
```
And this is error : 

```
_PROJECT_PATH_\Resources\Win32Manifest.rc: Error: Microsoft (R) Windows (R) Resource Compiler Version 6.3.9600.17298

Copyright (C) Microsoft Corporation.  All rights reserved.


 (_PROJECT_NAME_)
```

Oddly enough, there is application.exe file in bin\Debug folder that runs as proper Windows application.

Just to note : I'm using Xamarin Studio 5.7 (build 661) with D Language bindings 2.6 on Windows 8.1 x64

**Comment by aBothe** [comment]
You can change the path used to access rc.exe in the global D settings.
Then, can the project be executed after building inside mono-d? There probably is an outdated regex used.

**Comment by dsoronda** [comment]
I've added path in global D settings as you suggested and run build again and got same error.

![xamarinstudio_build_error](https://cloud.githubusercontent.com/assets/776370/5828300/cce62840-a102-11e4-8d36-98ad4812b006.png)

If I run rc with debug flag

```
"c:\Program Files (x86)\Windows Kits\8.1\bin\x86\rc.exe" /v /fo "_PROJECT_PATH_\obj\Debug\Resources.Win32Manifest.res" "_PROJECT_PATH_\Resources\Win32Manifest.rc"
```
Following by :
```
dmd.exe -debug -gc "main.d" "obj\Debug\Resources.Win32Manifest.res" "kernel32.lib" "gdi32.lib"  "-odobj\Debug" "-of_PROJECT_PATH_\bin\Debug\x_win32.exe" -w -vcolumns -L-L/su:windows -L-L/exet:nt
```
Everything builds correctly so I guess it is something with return codes to Xamarin studio.

**Comment by aBothe** [comment]
Alright, in v2.6.1 it should be fixed now. Please review.

**Comment by dsoronda** [comment]
Well actually it didn't.
But good news is that i found how to get successfull build :)

This are working build arguments :

```
/nologo /fo "$res" "$rc"
```

**Comment by aBothe** [comment]
That's the thing I was hoping for! :D

**Comment by aBothe** [comment]
It's part of v2.6.2 - unfortunately, I made the previous version 2.61, so you have to "downgrade" to 2.6.2 again :D

**Comment by dsoronda** [comment]
Yes, just removed plugin and add it again.
Close this task as resolved. :)
