### ISSUE TITLE
Support Coverage Highlighting

### ISSUE THREAD

**Issue by UplinkCoder** [aBothe/Mono-D#559]
Visual D already supports coverage highlighting.
http://www.dsource.org/projects/visuald/wiki/News36

The coverage files will only be produced at runtime. 
Therefore threre has to be a way to specifiy paramters for the executable.

please excuse poor wording :)

**Comment by UplinkCoder** [comment]
This is implemented

**Comment by aBothe** [comment]
Hmm? This is implemented?

**Comment by UplinkCoder** [comment]
yes it does look for the lst files and parses them
