### ISSUE TITLE
step by step debug

### ISSUE THREAD

**Issue by gedaiu** [aBothe/Mono-D#578]
Is it possible to do step by step debug in mono-d addin? If yes, how? if not, how I can debug the addin?

Thanks,
Bogdan

**Comment by aBothe** [comment]
If you're on linux, there is gdb support - although local variables aren't displayed very well (yet - my custom gdb addin extends the support for this feature, but it's still not completed).

**Comment by gedaiu** [comment]
I don't want to debug my D program, I want to debug the Addin itself. I cloned the source, opened the addin solution in xamarin studio, and now I want to debug it.. it is possible?

I managed to build the add in and start XS with the built addin... my question is, how I can debug the built addin?

Thanks,
Bogdan

**Comment by aBothe** [comment]
Oh, well, that's far more easy :)
I recommed you to put in symlinks from the XS/Addins-folder to your bin/Debug/-folder in your project repo in the following manner:
```
ln -s -d "/home/lx/Dokumente/Projects/GdbAddin/build" "/opt/mono/lib/monodevelop/AddIns/gdb.d"
ln -s -d "/home/lx/Dokumente/Projects/Mono-D/MonoDevelop.DBinding/bin/Debug" "/opt/mono/lib/monodevelop/AddIns/mono-d"
```
Then, you can just hit the Play-button in the open mono-d solution, and get another XS opened with the freshly built addin active & enabled.

**Comment by aBothe** [comment]
I hope this answers your question, I'll close it now.
