### ISSUE TITLE
dub: The Mono-D generator has been removed

### ISSUE THREAD

**Issue by zoujiaqing** [aBothe/Mono-D#582]
Error executing command generate: The Mono-D generator has been removed. Use Mono-D's built in DUB support instead.

**Comment by Orvid** [comment]
What are you doing to cause this error from within Mono-D?

**Comment by aBothe** [comment]
It's not an error. dub originally had a feature to generate a mono-d project definition file out of a dub project - but as this isn't needed anymore, this feature has been removed. Good to know.
