### ISSUE TITLE
build error markers have fixed font size when zooming

### ISSUE THREAD

**Issue by Trass3r** [aBothe/Mono-D#588]
Probably more of a MonoDevelop issue but I can't figure out how they call these things officially.
Those red markers in the source code for compiler errors don't change font size when zooming with Ctrl +

**Comment by aBothe** [comment]
You mean the marker description 'bubble' that is drawn right next to the codeline? I'm not sure whether this has ever been recognized as a problem - perhaps changing the menu font or other fonts might suffice.
