### ISSUE TITLE
version flags from dub.json not interpreted

### ISSUE THREAD

**Issue by Extrawurst** [aBothe/Mono-D#593]
repro: simply clone https://github.com/Extrawurst/unecht/
open sample project: https://github.com/Extrawurst/unecht/blob/master/samples/helloworld/dub.json
note how this project includes a specific version flag!

and browse to here:
https://github.com/Extrawurst/unecht/blob/master/source/unecht/glfw/application.d#L62

in the dependencies. this will look like this:
![image](https://cloud.githubusercontent.com/assets/776816/6788024/179ad0a6-d197-11e4-9f2f-85bfb81c1ca2.png)

**Comment by aBothe** [comment]
Well, using `version(UEIncludeEditor)` inside app.d in the sample project works well.
So it's only a question of inheriting version/debug conditions between projects or inside the dependency tree.
-- What if I had two sample projects using unecht as dependency, but only one sample app emitted `UEIncludeEditor` inside its config?

**Comment by aBothe** [comment]
Okay, for pure editing experience, not fading out any `version()`-block might be a solution.
But what about actual code resolution that is needed for completion that depends on version()-constraints?

**Comment by aBothe** [comment]
Preferring the 'startup'-project that is run when clicking the 'Play'-Button?
What about dependency tree messing.. I hate this crap.

**Comment by Extrawurst** [comment]
well it is not as if popular other D projects wouldn't use the same mechanism, see vibe.d's ```VibeDefaultMain```version flag:

https://github.com/rejectedsoftware/vibe.d/blob/master/examples/app_skeleton/dub.json#L12

**Comment by aBothe** [comment]
Soo.. quirk solution: Prefer the startup "Main" project, but ensure that the currently edited file is in a project that is a dependee of given Main project..or somewhere in between :/

**Comment by Extrawurst** [comment]
um... i have no idea ? is this advice how to workaround on my end or your thinking out loud how to "quirk" implement this ?

**Comment by Extrawurst** [comment]
cause in the given example case i cannot set anything else as a "main" project...?!

**Comment by Extrawurst** [comment]
great thanks!
