### ISSUE TITLE
type resolution for indirectly imported public-imports seems broken

### ISSUE THREAD

**Issue by Extrawurst** [aBothe/Mono-D#596]
regarding my github project (for repro: https://github.com/Extrawurst/unecht):

type ```vec3``` cannot be found (goto-def or something):
https://github.com/Extrawurst/unecht/blob/master/samples/helloworld/source/app.d#L29

the type get imported using ```import unecht```:
https://github.com/Extrawurst/unecht/blob/master/samples/helloworld/source/app.d#L3

which has a ```public import gl3n.linalg;``` and thats where type ```vec3``` is defined

see:
![image](https://cloud.githubusercontent.com/assets/776816/6825233/52d2681a-d2f9-11e4-8ab2-ed64b61ef664.png)

**Comment by aBothe** [comment]
The public import stuff is working - it's able to find UEComponent.
Couldn't it simply be the fact that gl3n is missing?

**Comment by Extrawurst** [comment]
maybe its because another third library is where vec3 is in and the unecht lib just publicly imports it?

**Comment by aBothe** [comment]
are you able to get completion for gl3n?

**Comment by Extrawurst** [comment]
now we get closer. yeah i dont get any completion for any lib that is not a DIRECT dependency of the helloworld app.

**Comment by aBothe** [comment]
Is any gl3n library shown in the project pad? Or can you access gl3n stuff from derelict sources?
It's a difference between having stuff loaded but not referenced and having it referenced but not loaded at all.

**Comment by Extrawurst** [comment]
gl3n shows up in the project pad perfectly fine..
![screen shot 2015-03-27 at 16 22 09](https://cloud.githubusercontent.com/assets/776816/6870610/7474bce8-d49d-11e4-86eb-f964800130ec.png)

why do we keep playing this q&a game when all u have to do to answer those questions is git clone and look for yourself ? :)

**Comment by Extrawurst** [comment]
and yes i get completion for gl3n stuff in the unecht-lib which is a dependency of helloworld

**Comment by Extrawurst** [comment]
so i guess the only question is: should mono-d autocomplete indirect dependencies that come two levels down the dependency tree. right now dub build this just fine so i guess mono-d should allow completion there too...

**Comment by aBothe** [comment]
This involves changing the entire API heavily..but well, let's see.

**Comment by aBothe** [comment]
There probably will be some null-ref-exceptions throwing around, but the unittests are passing.
Editing should work just as normal.

**Comment by Extrawurst** [comment]
the proposed use case (my helloworld app) still gives no completion for gl3n types.. please download the repro project
