### ISSUE TITLE
import autocompletion does not merge shared package names

### ISSUE THREAD

**Issue by Extrawurst** [aBothe/Mono-D#597]
application A has two dependencies that both live in sub packages of "derelict" - now the import completion shows "derelict" twice instead of merging everything thats found under "derelict"

see:
![screen shot 2015-03-27 at 13 51 40](https://cloud.githubusercontent.com/assets/776816/6868069/a5f8378c-d488-11e4-906b-99f70d8a388d.png)

**Comment by aBothe** [comment]
I bet this issue comes from different libraries that put stuff under said `derelict` package.

**Comment by Extrawurst** [comment]
yeah .. like i said "has two dependencies" aka libraries...

**Comment by aBothe** [comment]
You just caught me only looking at the image, not the description text :P
