### ISSUE TITLE
Completion for alias this

### ISSUE THREAD

**Issue by etcimon** [aBothe/Mono-D#598]
I rely a lot on the `alias this` overload method, especially when using reference counting. It basically works exactly like inheritance but for structs/classes and without the `override` when overriding a method.

At the moment I need to do this to have completion : 

`alias HTTPClientConnection = /*FreeListRef! disabled for IDE */HTTPClientConnectionImpl;`

Here's an example of how it should work:

```D
struct A {
	void hello();
}

struct AliasThis {
	alias this A;
}

void main() {
	AliasThis str;
	str.hello |
         //   ^ no completion
}
```

**Comment by aBothe** [comment]
Okay, a nicely reproducable test case. I even think that this should already work in some way.

**Comment by etcimon** [comment]
> Okay, a nicely reproducable test case. I even think that this should already work in some way.

Through the years, I think I've learned how to avoid over-complicating things. Examples should be 80% of the talk

To get back to this issue, I do believe the simplest implementation should also cover the most complex use cases, I wish I knew everything you know about the Mono-D's internals, so that I could pull it off myself :-p Have you considered writing a small wiki about the architecture of Mono-D and a reference to a similar guide for MonoDevelop? The source is a nice guide in itself, but sometimes you also need a higher-level view to have a chance at getting smart enough to grasp the structure and concepts that are used in it.

**Comment by aBothe** [comment]
Good idea.

**Comment by aBothe** [comment]
Is `alias this A;` correct? In my test cases, I only have `alias __conn this;`. Are both syntaxes allowed?

**Comment by etcimon** [comment]
Oh you're right, I always get it the other way around. It should be `alias A this`

Hmm, no idea why my FreeListRef is having issues then

**Comment by aBothe** [comment]
So, is it working then?

**Comment by etcimon** [comment]
Well yes and no, it's more of a complex issue than I thought

https://github.com/etcimon/vibe.d/blob/http2/source/vibe/http/client.d#L262

Completion doesn't work here if I use `FreeListRef` from here:

https://github.com/etcimon/vibe.d/blob/http2/source/vibe/http/client.d#L1117

Defined as alias this here:

https://github.com/etcimon/vibe.d/blob/http2/source/vibe/utils/memory.d#L700

I'll try and isolate it more

**Comment by etcimon** [comment]
It's the pointer type: 

```D
struct A {
	void hello();
}

struct AliasThis {
	@property A* get();

	alias get this;
}

void main() {
	AliasThis!A str;
	str.he
		//   ^ no completion
}
```

**Comment by aBothe** [comment]
In the actual code, will get() be executed then as soon as I try to access `hello`?

**Comment by etcimon** [comment]
Exactly.

Actually, the property feature works, it's only the pointer types:

struct A {
	void hello();
}
alias TR = A*;
struct AliasThis {
	alias TR this;
}

void main() {
	AliasThis str;
	str.hel
		//   ^ no completion
}

**Comment by aBothe** [comment]
it's part of v2.10.3

**Comment by etcimon** [comment]
The test works but that doesn't solve my issue :( I found out that the `alias get this` has a `@property const(TR) get();` overload and the mix of both, const and non-const options is enough to break the completion. Here's a test:

```D
struct A {
	void hello();
}

struct AliasThis {
	@property const(A) get() const;
	@property A get();
	alias get this;
}

void main() {
	AliasThis str;
	str.hel
    //   ^ no completion
}
```

**Comment by aBothe** [comment]
I thought we'd left this age of const-everywhere-ness that makes the entire code unreadable.

**Comment by etcimon** [comment]
> I thought we'd left this age of const-everywhere-ness that makes the entire code unreadable.

Hmm, I don't think it's a bad thing to have const-ness, and it does make `in param` work correctly. I'm not sure how I could rewrite that overload for the completion to work with freelists, is it easy to fix on the IDE?

**Comment by aBothe** [comment]
I could discard any second findings for now, or enum through all found `get`-overloads. What would you prefer?

**Comment by etcimon** [comment]
Discard second findings, no chances for duplicates that way I guess?

**Comment by aBothe** [comment]
I just want a rather elegant code on how to handle these alias-this definitions, that's it :smile:

**Comment by aBothe** [comment]
v2.10.4

**Comment by etcimon** [comment]
![awesome](http://memecrunch.com/meme/CNSF/why-the-hell-are-you-so-awesome/image.jpg)

**Comment by aBothe** [comment]
Nah, I'm not proud of how I've fixed this.. just another foreach and likely incomplete state gathering - that's bad :/

**Comment by etcimon** [comment]
> Nah, I'm not proud of how I've fixed this.. just another foreach and likely incomplete state gathering - that's bad :/

It's not a compiler, yet I'm not even bothering to compile more than once a month anymore. I can't find anything else bothering me in the IDE. Except maybe the lack of docs, maybe I can take a few months to write them and clean up in a few months once I'm done with the whole web stack and my main project.
