### ISSUE TITLE
Cannot go to definition on std.

### ISSUE THREAD

**Issue by etcimon** [aBothe/Mono-D#599]
I'm not sure it's a regression, but the phobos/druntime types don't get resolved anymore and I can't quite find which commit broke this.

**Comment by etcimon** [comment]
It all works until this commit:

https://github.com/aBothe/D_Parser/commit/a3e328a74ad9c87fbd31f74b9dd2bac0f0d4f197

**Comment by aBothe** [comment]
Indeed, now I'm noticing it as well.. it's not showing any phobos stuff. Gonna do this tomorrow.

**Comment by etcimon** [comment]
Yeah, I just git cherry-picked the last 3 commits you did for alias this, and put them on top of the commit before a3e328a, and so everything works as I need it =)
