### ISSUE TITLE
Wrong dub package version loaded in project pad

### ISSUE THREAD

**Issue by aka-demik** [aBothe/Mono-D#608]
When I open a dub-project using vibe.d, in the external dependencies loaded version vibe-d-0.7.21.
But in my dub.json: `"vibe-d" : "~> 0.7.23"`. 
And when building dub using "0.7.23".
![ha](https://cloud.githubusercontent.com/assets/5939623/7470220/9d26ed38-f323-11e4-9260-af9bf134adc4.png)
Naturally, the problem occurs only if I have multiple versions of vibe.d installed.

**Comment by aBothe** [comment]
Could you have a look where dub parses or compares a package's version?

**Comment by aka-demik** [comment]
Maybe to not duplicate the DUB implementation, read the selected version from the file "dub.selections.json"?
Or better yet, read the output of `dub describe`. This command prints the json with complete list of used packages.

**Comment by aka-demik** [comment]
Thank you.

**Comment by aBothe** [comment]
I tested some cases successfully, I hope they gonna work for most of the other use cases.
