### ISSUE TITLE
parameter completion for function pointer call

### ISSUE THREAD

**Issue by Extrawurst** [aBothe/Mono-D#614]
since fixing #613 solved some issues on finding the declaration of function pointers in libraries now the completion for parameters of calling those is wrong:
![screen shot 2015-05-29 at 12 33 38](https://cloud.githubusercontent.com/assets/776816/7881050/6a94c0b8-05ff-11e5-96b4-5cbee9654ced.png)

Compare this to a regular function call:
![screen shot 2015-05-29 at 12 33 20](https://cloud.githubusercontent.com/assets/776816/7881062/7804164a-05ff-11e5-952a-0fea92aadfb3.png)

both examples again in app.d of the imgui_d_test project: https://github.com/Extrawurst/imgui_d_test

**Comment by aBothe** [comment]
Should be fixable via resolving aliases when gathering the parameter info.

**Comment by Extrawurst** [comment]
what ever works for you ^^

**Comment by aBothe** [comment]
Delegate types are rendered now just as normal methods now in tooltips.

**Comment by Extrawurst** [comment]
awesome, in which release is it ?

**Comment by aBothe** [comment]
2.13
