### ISSUE TITLE
Cannot catch multiple definitions of shared constructor

### ISSUE THREAD

**Issue by tcak** [aBothe/Mono-D#615]
In the module "com.abcdef.caterpil.target.templatefileresource", in class "PlaceHolderTemplate", by mistake, I have defined same shared constructor twice.

public this() shared{}

When I tried to compile it, error message was as follows and it wasn't handled. Is it possible to parse this error message for better error information?

dmd "@/tmp/tmp430df3b7.tmp"
obj/Release/SampleTarget3.o: In function `_D3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate6__ctorMOFZOC3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate':
/home/muser/dev/d/libraries/com/abcdef/stringutils/split.d:(.text._D3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate6__ctorMOFZOC3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate+0x20): multiple definition of `_D3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate6__ctorMOFZOC3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate'
obj/Release/SampleTarget3.o:/home/muser/dev/d/libraries/com/abcdef/stringutils/split.d:(.text._D3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate6__ctorMOFZOC3com6abcdef9caterpil36target20templatefileresource19PlaceHolderTemplate+0x0): first defined here
collect2: error: ld returned 1 exit status

**Comment by Extrawurst** [comment]
thats a linker error and mono-d does not parse those (yet)

**Comment by aBothe** [comment]
Oh, thanks for the hint - yeah, ld errors aren't handled yet.

**Comment by Extrawurst** [comment]
ld, optlink, u name it. sure you want to implement all their formats ? ;)

**Comment by aBothe** [comment]
Everything that fits into a regex :P
