### ISSUE TITLE
Wrong extension used for shared libs on OSX

### ISSUE THREAD

**Issue by bitwise-github** [aBothe/Mono-D#616]
shared libs get ".so" extension instead of ".dylib"

**Comment by bitwise-github** [comment]
Mac OSX Yosemite

**Comment by aBothe** [comment]
Hmm, I thought I put in .dylib-extensions already. Perhaps the OS-check is failing.

**Comment by bitwise-github** [comment]
Console.WriteLine(Environment.OSVersion);
I get "Unix"....
That can't be right

**Comment by bitwise-github** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=13345

**Comment by bitwise-github** [comment]
This seems to work:

*Add reference to 'Mono.Posix'

    using System;
    using Mono.Unix.Native;

    namespace PlatformTest
    {
        class MainClass
        {
            static bool IsMac()
            {
                if(Environment.OSVersion.Platform != PlatformID.Unix)
                    return false;
            
                Utsname results;
                Syscall.uname(out results);
                return results.sysname == "Darwin";
            }

            public static void Main(string[] args) {
                Console.WriteLine(IsMac());
            }
        }
    }

**Comment by bitwise-github** [comment]
https://github.com/aBothe/Mono-D/pull/617

I figured I should let you add the reference to Mono.Posix.dll yourself.
Please see comments on pull request.

**Comment by aBothe** [comment]
This issue should be solved now.

**Comment by bitwise-github** [comment]
:+1:
