### ISSUE TITLE
[osx] building does not work anymore

### ISSUE THREAD

**Issue by Extrawurst** [aBothe/Mono-D#625]
related to #517 i guess.
the regular setup with mono-d gives:
```
dub build "derelict-steamworks" "--build=plain"
Error executing command build:
Failed to invoke the compiler dmd to determine the build platform: /bin/bash: dmd: command not found
```

after creating a script `monod_dub.sh` in home folder with the following content:
```
#!/bin/sh
export PATH="$PATH;/usr/local/bin"
dub $*
```

and setting dub exec path to `~/monod_dub.sh` gives:

```
~/monod_dub.sh build "derelict-steamworks" "--build=plain"
/bin/sh: ~/monod_dub.sh: No such file or directory
Exit code 127
```

**Comment by Extrawurst** [comment]
ok two mistakes:
1) the content of the script needs to be:
```
#!/bin/sh
export PATH="$PATH:/usr/local/bin"
dub $*
```

2) the dub exec in monod cannot resolve `~` so the path has to look like `/Users/<user>/monod_dub.sh`

**Comment by p0nce** [comment]
I've hit the very same problem. @Extrawurst's solution works well, but the Wiki doesn't say a thing about this.

**Comment by aBothe** [comment]
I may extend the wiki then.

**Comment by aBothe** [comment]
@p0nce  http://wiki.dlang.org/Mono-D#Dub_can.27t_find_dmd :smile:

**Comment by p0nce** [comment]
Thanks.
