### ISSUE TITLE
versioned block weird output

### ISSUE THREAD

**Issue by rikkimax** [aBothe/Mono-D#633]
So I was porting sljit to D (because why not) and on the second file it decided that:

```D
static if(SLJIT_CONFIG_AUTO) {
    version(Windows) {

    } else {
        version(X86) {
            enum SLJIT_CONFIG_X86_32 = true;
        }{
        version(X86) {
            enum SLJIT_CONFIG_X86_32 = true;
        } else version(X86_64) {
            enum SLJIT_CONFIG_X86_64 = true;
        }
    }
}
```

Would appear as:

![capture](https://cloud.githubusercontent.com/assets/992755/11417126/d206540c-9478-11e5-834c-c73be839b92e.PNG)

**Comment by aBothe** [comment]
This is not a bug but a feature called conditional highlighting. It can be disabled in the D settings via the 'Enable Conditional Highlighting' flag

**Comment by aBothe** [comment]
anyway, :+1:  for the 'because why not' :smile:
