### ISSUE TITLE
Unable to create D project

### ISSUE THREAD

**Issue by leh103** [aBothe/Mono-D#635]
This is the error I get when trying to create a new d project. I am using monodevelop 5.9 and the latest d language bindings. See attachment:

[monodevelopDcreatProjectError.txt](https://github.com/aBothe/Mono-D/files/79020/monodevelopDcreatProjectError.txt)

**Comment by aBothe** [comment]
Hmm, seems I need to link against the asp-libraries as well >_>

**Comment by leh103** [comment]
Sorry about the typo, it is version 5.8 of Monodevelop I am using on a 32 bit mintlinux box. I checked my Monodevelop on my 64 bit laptop with mintlinux. It has version 5.3 of Monodevelop and a older version of mono-d and it compiles the console app provided OK. However, if will not compile visual basic because of an error in the build configuration. The Monodevelop 5.8 does compile visual basic OK although it is a old version of vb. I was hoping to be able to compile C++, C#, VB and D on the same IDE. On my windows partitions with Xamarian all works fine.

**Comment by aBothe** [comment]
Okay, yeah, MonoDevelop 5.9 is mandatory, not any older version. You may close this issue then.

**Comment by leh103** [comment]
As far as I know MonoDevelop 5.8 is the lastest version. I just 
downloaded it the day I opened this issue. I noticed that you closed 
this issue, but for me I still have this problem.

**Comment by aBothe** [comment]
According to http://www.monodevelop.com/download/, it's 5.10

**Comment by leh103** [comment]
Actually, on the mint and ubuntu repositories the latest is version 
4.0.1 something. I just checked today. The one I am using is the tar 
file at http://simendsjo.me/files/abothe which is version 5.8 from 2015 
or 2014. This installs in the /opt directory. I could install the 
version in the repositories and install an older mono-d file, but if I 
remember it had version troubles. The windows versions I have work fine 
and are version 5.10.

**Comment by aBothe** [comment]
Oh okay, so I got to update the setups again..let's see whether I get all the dependencies gathered :smile:

**Comment by leh103** [comment]
Actually, I must apologist. The latest MonoDevelop is version 5.10. I 
just had to follow the instructions on the Debian and Ubuntu download 
page at http//www.monodevelop.com/download page, which is what you 
suggest. I got MonoDevelop version 5.10 downloaded and installed. Of 
course mono-d works great now. I like Xamarian/Monodevelop because I can 
use the same IDE on Windows and Linux. With mono-d I can code in C, C++, 
C#, VB and D on both platforms with the same IDE. So thanks for the 
great extension to MonoDevelop.

Larry

**Comment by aBothe** [comment]
Alright, no problem. You're welcome.
