### ISSUE TITLE
Debuging under windows

### ISSUE THREAD

**Issue by Rikarin** [aBothe/Mono-D#638]
I cannot `start debugging` under windows. Why I cannot use windbg as a main debugger in XS? 
I can easily debug my app with visual studio. Its little annoying when I always must switch from XS to VS when I wanna debug couple lines of code.

**Comment by aBothe** [comment]
Hi there, debugging is not supported on Windows, neither or only partwise on Linux.
There has been support for debugging D programs some time ago, but then there rose issues with C++/CLI compatibility, VC++ redistributables and the interfaces between Microsoft's DbgEngine and MonoDevelop/XamarinStudio, so I got fed up with that and discontinued it.
Atm I'm too lazy to do anything about this + now that there's VisualD's support, I don't want to do reinvent the wheel.
