### ISSUE TITLE
Does Mono-D Support Debugging for now?

### ISSUE THREAD

**Issue by aokman** [aBothe/Mono-D#640]
I visited http://mono-d.alexanderbothe.com/wordpress/tag/debugging/. It seems Mono-D supported debugging before.

But I try Mono-D on both Mac OSX and Windows. The command Run > Start Debugging is always greyed out.

Does Mono-D Support Debugging for now?

**Comment by Rikarin** [comment]
#638 Same unanswered question.

**Comment by aBothe** [comment]
See #638
