### ISSUE TITLE
dependencies shown multiple times

### ISSUE THREAD

**Issue by Extrawurst** [aBothe/Mono-D#642]
see derelict-util dependency here here:
<img width="887" alt="screen shot 2016-02-10 at 21 52 29" src="https://cloud.githubusercontent.com/assets/776816/12961426/b263ec50-d040-11e5-9354-ab2b3180d4a4.png">

for repro load https://github.com/Extrawurst/unecht/blob/master/samples/helloworld/dub.json

**Comment by aBothe** [comment]
Just tried opening & even building unecht while fixing #643 and didn't notice mono-d loading derelict-util more than once. Seems to be fixed then! :)
