### ISSUE TITLE
Illegal Token

### ISSUE THREAD

**Issue by dariusc93** [aBothe/Mono-D#645]
Not completely sure why but when I try to open a dub project I get "Load operation failed. Illegal token on subpackage definition beginning". I did upgrade to the latest plugin which did fix #643

**Comment by Trollgeir** [comment]
I still have this problem, it was introduced at version 2.14.0 or 2.14.1 I believe.

**Comment by dariusc93** [comment]
@aBothe

**Comment by dariusc93** [comment]
Hmm looks like removing everything and reinstalling monod fixed it..
