### ISSUE TITLE
error opening dub.json project Illegal Token  for windows monod ver 2.14.2

### ISSUE THREAD

**Issue by shumtn** [aBothe/Mono-D#647]
Xamarin Studio ver:5.10.2
mono-d ver:2.14.2
opening dub.json project
error: "Load operation failed. Illegal token on subpackage definition beginning"
Expect an emergency fix this error Thank you！

**Comment by shumtn** [comment]
1、dub init test  
open dub.json [success]
2、dub init test -t vibe.d
open dub.json error

**Comment by aBothe** [comment]
I'm on it.
Unfortunately, I've begun now to rewrite further parts of the dub.json parse stuff, so it'll still take some time for me to develop and test it.

**Comment by aBothe** [comment]
Related to #646

**Comment by shumtn** [comment]
come on ab[Alexander Bothe] i love you!

**Comment by aBothe** [comment]
Please give v2.14.3 a go

**Comment by shumtn** [comment]
thx ab you are the best
