### ISSUE TITLE
Configuration Error: Compiler is not properly called

### ISSUE THREAD

**Issue by L0g4n** [aBothe/Mono-D#649]
Hi Guys,

tried Mono-D today for the first time. So I wanted to compile a sample project, but out of the build output I realized that the Compiler is not properly called. It just calls the compiler with `dmd -debug` but not with the files as arguments that have to be compiled.
So I think this is just a config error, so how can I set up this properly ?

**Comment by aBothe** [comment]
Hi, is it? I haven't tested the native mono-d project support for ages, all I recently was up to was to support dub and all its features. So, I'd recommend getting your hands on dub and its infrastructure, then using mono-d on top of dub.

**Comment by L0g4n** [comment]
Hi,
how can I do that ? Is there a addin for dub in XS ?
I just began to work with the D programming language so I only know that DUB is smt. like Maven for java.

**Comment by aBothe** [comment]
well, mono-d is actually able to handle dub.json or dub.sdl files as project files and thus can open them like normal projects (read-only by design though).

All you may do is to 
+ install dub, for instance via your favorite package manager or from over [here](http://code.dlang.org/download)
+ open up a command line and type 'dub init MyProject'
+ open the dub.sdl that is inside the newly created MyProject-folder inside Mono-D (via regular Ctrl+O I suppose)
+ code & build stuff

Note though that there's no proper debugging functionality built in mono-d atm, pretty much due to my lazyness and economic proportioning of my spare time :stuck_out_tongue: 
Still, there's Visual D and gdb on linux.

**Comment by aBothe** [comment]
Still, if you like coding for D in like C#, just take a look on Mono-D's source code. The parser and code completion resolution part is somewhat magic :)

**Comment by L0g4n** [comment]
OK, made that so far.
But compiling through the IDE still does not work. Error Message: "The invoked target caused an exception.". And when I click on the "Code" tab in XS, there are the comments:
"// No matching .lst-file found!
// Build & execute your project with e.g. dmd's `-cov` flag set!"

**Comment by aBothe** [comment]
"The invoked target caused an exception" -- this is strange. On which OS are you working?

The 'dmd -cov' thing is for code coverage highlighting purposes and purely optional, so not related to the current problem.

**Comment by L0g4n** [comment]
I'm currently on Windows 10.

**Comment by aBothe** [comment]
For me, building & executing a dummy dub project works flawlessly. Hmm.
There's a build log that can be displayed and there are logs that can be read in order to get the error message. Dub can be accessed via %PATH%, right?
![2016-03-08 20_41_57-myprj - source_app d - xamarin studio](https://cloud.githubusercontent.com/assets/1143073/13613888/3f9f8dda-e56e-11e5-989f-ce3c180388a3.png)

![2016-03-08 20_41_11-fotos](https://cloud.githubusercontent.com/assets/1143073/13613862/26be6fd4-e56e-11e5-9e2a-88a809eca714.png)

**Comment by L0g4n** [comment]
Hi,
yeah dub directory is in the PATH variable.
I think this is the suitable exception message:

> ERROR [2016-03-08 21:27:11Z]: System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei MonoDevelop.D.Profiler.Gui.ProfilerPadWidget.Build()
   bei MonoDevelop.D.Profiler.Gui.ProfilerPadWidget..ctor(DProfilerPad pad)
   bei MonoDevelop.D.Profiler.Gui.DProfilerPad..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei Mono.Addins.RuntimeAddin.CreateInstance(String typeName, Boolean throwIfNotFound)
   bei MonoDevelop.Ide.Codons.SolutionPadCodon.CreatePad()
   bei MonoDevelop.Ide.Codons.PadCodon.InitializePadContent(IPadWindow window)
   bei MonoDevelop.Ide.Gui.PadWindow.CreateContent()
   bei MonoDevelop.Ide.Gui.PadWindow.get_Content()
   bei MonoDevelop.Ide.Gui.Pad.get_Content()
   bei MonoDevelop.D.Profiler.Commands.ProfilerModeHandler.set_IsProfilerMode(Boolean value)
   bei MonoDevelop.D.Projects.Dub.DubBuilder.BuildCommonArgAppendix(StringBuilder sr, DubProject prj, ConfigurationSelector sel)
   bei MonoDevelop.D.Projects.Dub.DubBuilder.BuildProject(DubProject prj, IProgressMonitor mon, ConfigurationSelector sel)
   bei MonoDevelop.D.Projects.Dub.DubProject.DoBuild(IProgressMonitor monitor, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.Project.OnBuild(IProgressMonitor monitor, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.SolutionItem.OnRunTarget(IProgressMonitor monitor, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.SolutionEntityItem.OnRunTarget(IProgressMonitor monitor, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.Project.OnRunTarget(IProgressMonitor monitor, String target, ConfigurationSelector configuration, TargetEvaluationContext context)
   bei MonoDevelop.Projects.Project.OnRunTarget(IProgressMonitor monitor, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.DefaultProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, SolutionEntityItem item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.CustomCommandExtension.Build(IProgressMonitor monitor, SolutionEntityItem entry, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.Build(IProgressMonitor monitor, IBuildTarget item, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.ProjectServiceExtension.RunTarget(IProgressMonitor monitor, IBuildTarget item, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.SolutionItem.RunTarget(IProgressMonitor monitor, String target, ConfigurationSelector configuration)
   bei MonoDevelop.Projects.SolutionItem.Build(IProgressMonitor monitor, ConfigurationSelector solutionConfiguration, Boolean buildReferences)
   bei MonoDevelop.Projects.SolutionItem.Build(IProgressMonitor monitor, ConfigurationSelector solutionConfiguration, Boolean buildReferences)
   bei MonoDevelop.Projects.SolutionItem.Build(IProgressMonitor monitor, ConfigurationSelector solutionConfiguration, Boolean buildReferences, ProjectOperationContext context)
   bei MonoDevelop.Ide.ProjectOperations.BuildSolutionItemAsync(IBuildTarget entry, IProgressMonitor monitor, ITimeTracker tt, Boolean skipPrebuildCheck, ProjectOperationContext context)

**Comment by aBothe** [comment]
Weird issue, never had this before. Oh boy.

**Comment by L0g4n** [comment]
That does not sound good. Is it an error I can fix by myself ?

**Comment by aBothe** [comment]
Please activate the D Profiler pad for once, then we'll see if it crashes again - as its GUI constructor might be corrupted by some magic side effects.
![2016-03-08 22_08_24-myprj - source_app d - xamarin studio](https://cloud.githubusercontent.com/assets/1143073/13616463/5bdb442e-e57a-11e5-8ff4-19ba3ded3140.png)

**Comment by L0g4n** [comment]
Hey,
surprisingly it works now flawlessly.
So do I have to enable the D Profiler every tme again ?

**Comment by aBothe** [comment]
Just leave it open as some pad in the background - it'll be opened on the next launch of XS.
