### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by Rikarin** [aBothe/Mono-D#650]
Support for cmake projects would be fine like in Netbeans. With option "Create a new project with existing cmake files." and then just call cmake and compile sources with make for D.

**Comment by aBothe** [comment]
cmake? Hmm. For convenience and portability reasons, I'd rather try to build a script or program that converts cmake files into dub.json/sdl definitions, at least for the D part of your target project.

Digging into interpreting cmake files, structures and build patterns is a probably too heavy feature to lift on my own -- it would attract too many new bugs and issues + the actual benefit isn't outweighing the necessary efforts; Cmake doesn't seem to be used widely in D(?) anymore(?).

**Comment by Orvid** [comment]
You'd be much better off having CMake generate a project file for Visual Studio, no idea how well that would work for D though. With CMake it's generally done such that CMake generates the project files, not the individual IDE's. CMake has never been widely used with D.

If you really wanted to implement CMake projects, the best approach would be to instead support makefile projects, and let CMake generate a makefile for it.

**Comment by aBothe** [comment]
IIRC, Mono-D already had some sort of makefile generation support back then (which I removed again for unpopularity reasons).
Despite that, you may create a normal D Project inside Mono-D, enter 'make'/'make run' as build/run commands, and have all the work done right now, without implementing further things.

**Comment by Rikarin** [comment]
But IDE like netbeans just use cmake to generate makefiles for compiling, then create nbproject and use that makefile.

**Comment by Rikarin** [comment]
but it was only idea. And I missed that fact there is a dub system.
