### ISSUE TITLE
Mono-D not available/working for Xamarin Studio Community 6.1

### ISSUE THREAD

**Issue by bitwise-github** [aBothe/Mono-D#656]
I was sure I had Mono-D installed..but it seems to have disappeared. I don't see it in the gallery either(no language binding category at all). XS seems to be in total chaos lately, so it's entirely possible there is nothing wrong with Mono-D, but XS also could have broken compatibility.

**Comment by bitwise-github** [comment]
When I tried to build Mono-D and install it myself, I got this:

> required: MonoDevelop.Ide,5.0, found: MonoDevelop.Ide,6.1
> required: MonoDevelop.Core,5.0, found: MonoDevelop.Core,6.1

So I updated the dependancies, and it seems a lot has changed. For example, 'ILanguageBinding' is now 'LanguageBinding'.

**Comment by bitwise-github** [comment]
So I guess this is a duplicate?
https://github.com/aBothe/Mono-D/issues/648

I was sure I had Mono-D working with Xamarin Studio Community at some point.

If you're already working on this, I will close this.
Thanks

**Comment by NightmareX1337** [comment]
You're right, Xamarin Studio (and MonoDevelop) have seamlessly broken it's API, in a way that we think it's probably better to rewrite it, 'cause that's gonna happen anyway. (API breakage is ridiculously big)

**Comment by bitwise-github** [comment]
Not sure I understand. Do you mean that you guys aren't going to update because they make too many breaking changes? I'm confused because I based on the current state of XS, I don't see a second option beside heavy duty rewrite.

**Comment by NightmareX1337** [comment]
We're either going to rewrite (let's hope we can handle it) or we will do our best to migrate existing code base to work with the new API. I was just saying since API breakage is high, a fresh write might be better.

**Comment by bitwise-github** [comment]
Ok thanks

**Comment by etcimon** [comment]
> We're either going to rewrite (let's hope we can handle it) or we will do our best to migrate existing code base to work with the new API. I was just saying since API breakage is high, a fresh write might be better.

Don't. It's a waste of time, the team behind MonoDevelop obviously doesn't care about breaking everything repeatedly. I would suggest porting it to Visual Studio Code or IntelliJ if you absolutely itch to do major changes. Until then, I'd focus on making Mono-D & MonoDevelop 5.10 easier to setup for new users, as there is no more valid installation instructions.
