### ISSUE TITLE
Can't install on OSX because of missing dependencies

### ISSUE THREAD

**Issue by p0nce** [aBothe/Mono-D#660]
I'll paste the whole error message here if needed.

**Comment by nicolasjinchereau** [comment]
Unfortunately, large breaking changes to Xamarin's plugin API have rendered this plugin out of date. Large portions of it have to be rewritten before it will work again.

https://github.com/aBothe/Mono-D/issues/648

**Comment by aBothe** [comment]
Hey there, I currently don't think I'll do this any time soon.
I think, like @nicolasjinchereau mentioned the foregoing discussion thread, Mono-D needs an overall rewrite or rebase on a different IDE or something similar.
I won't do this full-time advantage anymore 🤕 , sry.

**Comment by p0nce** [comment]
No problem. Thanks for the amazing work @aBothe ! I will try to get Xamarin 5.10 :)
